[package]
name = "arshin"
authors = ["Stanislav Khristoforov <stnslv91@gmail.com>"]
version = "0.2.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
pest = "2.8.1"
pest_derive = "2.8.1"
thiserror = "2.0.12"
